### PR TITLE
More translated items to Catalan and Spanish languages.

### PR DESCRIPTION
**Pull request by eldelinux**
More translated items (voice commands, gamepad preferences and consist menus) to Catalan and Spanish languages, and many others minor corrections.

### CODE REVIEW

**Comment by flash62au** [comment]
Hi,
I hadn't realised this PR was here.  
I have duplicated almost all of your changes in a separate PR, which should address the conflicts.  If I have done it right, the remaining ones are non-translatable, so should not have been included. 

Once Steve has accepted my PR, check that everything necessary is in there and you can probably just cancel your PR.

Peter

**Comment by eldelinux** [comment]
Hi Peter.

Thanks to answer my PR. OK, I 'm waitting to Steve do the new PR, and then I check translation.

Luis Zamora.

**Comment by mstevetodd** [comment]
I have merged Peter's PR.

**Comment by eldelinux** [comment]
Ok Steve.

Tomorrow I check ES translation of /src/main/res/values-es/strings.xml file.

**Comment by eldelinux** [comment]
Ok Steve.

Tomorrow I check ES translation of /src/main/res/values-es/strings.xml file.

**Comment by eldelinux** [comment]
Steve and Peter.

I have reviewed the changes to the values-es/strings.xml and values-ca/strings.xml files, both files are correct, except for the prefKidsHelpSummary line, this line causes a problem when translating it because it exceeds the line limit (10 lines), I have modified it but the PR of Peter is not this change.

How can we solve it?

Luis Zamora.

**Comment by mstevetodd** [comment]
I would suggest closing #467 and creating a new PR with just the needed changes.

**Comment by eldelinux** [comment]
Ok. I close this PR and tomorrow I will open a new PR with this changes.

Luis Zamora.

**Pull request closed without merging**
