### PR TITLE
fix - Maximum Throttle Percentage did not allow 100%

### PR DESCRIPTION
**Pull request by flash62au**
preference was set to only a length of 2

### CODE REVIEW

**Comment by mstevetodd** [comment]
Peter, you should add an edit to prevent > 100%. IIRC, the 2-digit max was my lazy way to edit that. :)

**Comment by flash62au** [comment]
Hi,
There already was code in there to prevent greater than 100. Is it not
working?

Peter

**Comment by mstevetodd** [comment]
I will merge and give it a try later today or tonight. Thanks.

**Comment by flash62au** [comment]
Seems as though the existing code works, but doesn't reload the preferences
page. So you only notice that it did anything after you exit the
preferences page and come back in again.

I will add the reload, and a toast message to say what it has done.


Peter

On 5 Dec. 2017 11:56 pm, "flash62au" <notifications@github.com> wrote:

Hi,
There already was code in there to prevent greater than 100. Is it not
working?

Peter

On 5 Dec 2017 11:02 PM, "SteveT" <notifications@github.com> wrote:

> Peter, you should add an edit to prevent > 100%. IIRC, the 2-digit max was
> my lazy way to edit that. :)
>
> —
> You are receiving this because you authored the thread.

> Reply to this email directly, view it on GitHub
> <https://github.com/JMRI/EngineDriver/pull/118#issuecomment-349297685>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-
auth/Ab2OA3Q51Pk9fKHmtXiNxp6_o2fbTKV9ks5s9T7igaJpZM4Q2Ik7>
> .

>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JMRI/EngineDriver/pull/118#issuecomment-349311146>, or mute
the thread

**Comment by n3ix** [comment]
Peter,

 

Seems like there should be a way to just invalidate the particular control in question so that it gets redrawn?

 

Robin

**Comment by flash62au** [comment]
I'll have a look.

Peter

**Comment by flash62au** [comment]
Hi,
The new PR should cover it.

Peter

**Pull request merged**
