### PR TITLE
NEW - Optional high contrast colour theme

### PR DESCRIPTION
**Pull request by flash62au**
(requires a restart after selecting in the preferences)

### CODE REVIEW

**Comment by n3ix** [comment]
Why does this change require changing the default Text for each Throttle Loco?

**Comment by flash62au** [comment]
It should not have actually changed. I just moved all the settings to a
style so that I can change them, by just switching the style.

Did something change?

Peter

**Comment by n3ix** [comment]
In throttle.xml, the following line was deleted in 3 places.  I did not see it added anywhere?

-                            android:text="@string/loco"

**Comment by flash62au** [comment]
Ok. Sounds like a mistake on my part.
I will look at it tonight


Peter

**Comment by flash62au** [comment]
In this first set of diffs it shows them as being *deleted*, then a few
lines below they show as *added*.
https://github.com/JMRI/EngineDriver/pull/137/files#diff-7

[image: Inline images 1]

[image: Inline images 2]

[image: Inline images 3]

Those lines are definitely in the final version

Peter

**Comment by n3ix** [comment]
@flash62au Ok, I see it now.  Thanks Peter.

**Comment by flash62au** [comment]
An APK with the two new themes is here if you want to try it...
https://drive.google.com/file/d/0B3ozBbgISK9qZnl0Y0Zfc3MwNVE/view?usp=sharing_eil&ts=5a6ab2bb

It is signed with my own personal keys so you will need to uninstall the 'normal' version first.
Peter

**Pull request merged**
