### PR TITLE
WIP:Catalan & Spanish Translation

### PR DESCRIPTION
**Pull request by eldelinux**
Little corrections in strings.xml and arrays.xml files.

### CODE REVIEW

**Comment by flash62au** [comment]
Luis,
do you need help retrieving your PR to fix the issue?

Peter

**Comment by eldelinux** [comment]
Hi Peter.

Many thanks for your help, I'm very busy with other projects, but that you says, I need help.
All my PR with Android Studio have the same problem, the problem is that the "PR deletes gradlew.bat".
What's gradlew.bat?. I don't know what I'm doing wrong. Can you tell me what I should do?.

Many thanks.

**Comment by eldelinux** [comment]
Hi Peter.

Many thanks for your help, I'm very busy with other projects, but that you says, I need help.
All my PR with Android Studio have the same problem, the problem is that the "PR deletes gradlew.bat".
What's gradlew.bat?. I don't know what I'm doing wrong. Can you tell me what I should do?.

Many thanks.

**Comment by flash62au** [comment]
Hi,
We had this problem (and with some other files) with the switch to the
Gradle build system/process and it took quite a while and a lot of mucking
around to resolve. Basically some files should be ignored but are not
because of when they were created and when they were added to the ignore
list.

It may prove easiest to delete your fork on github, rename your local copy
and essentially start again with a new local copy and a new fork.  As long
as you rename (rather than delete) your old local copy you can use the
'Compare Directories' plugin to help re-do your changes.

Peter

**Comment by eldelinux** [comment]
Hi Peter.

Many thanks for your advice, as soon as I can, I try to solve the problem.

Luis Zamora.

**Comment by eldelinux** [comment]
Hi.
I 'm deleted my fork of ED in GitHub, I have created a new fork, and with AS when export the fork to local copy in the PC, the AS ask me for Gradle configuration, as the image follow:

What I do?.
deepinscreenshot_20190102153703
Luis Zamora (eldelinux).

**Comment by flash62au** [comment]
hi,
Sorry I do this very infrequently, so I am not good at it.

try it the other way...
From AS, select File-> New -> Project From Version Control -> Git ->
(See the old instructions below)

You may end up needing to install Gradle locally, but you shouldn't have
to.  Don't do that unless we can't get it to work the other way.  (Google
it then download and install it)

Peter


For Android Studio.

Here are all the steps needed:

   -

   Install Android Studio.
   -

   Install GitGui.
   -

   On your phone make sure that the developer options are enabled and
   ‘Android debugging’ is on, and ‘unknown sources’ is on.
   -

   Connect your phone via USB.
   -

   Open Android Studio (if necessary, close any open project and restart,
   so you get the Welcome Wizard)
   -

   "Check out project from Version control" -> Git
   In the Clone Repository window, enter the Git Repository URL:
   https://github.com/JMRI/EngineDriver, -> Clone
   -

   Open the project.
   Take the Run -> Run... -> Edit Configurations option
   -

   In the Run/Debug Configurations window, press the "+", then Android App
   Enter Name "EngineDriver", and select Module: EngineDriver
   -

   Click Run.
   -

      You will likely get one or more error messages about missing
      components.
      -

      Click on the link in each message and Android Studio will
      automatically download the missing components.
      -

   In the Select Deployment Target window, your attached phone should show
   under Connected Devices.
   -

   Select your device and press OK.
   EngineDriver should compile and be installed on your device.


Use the Git GUI's Remote option to create two remotes:
jmri     https://github.com/JMRI/EngineDriver
<<yourGitHubName>> https://github.com/<<yourGitHubName>>/EngineDriver
<https://github.com/mstevetodd/EngineDriver>

(e.g. mstevetodd    https://github.com/mstevetodd/EngineDriver)


Back in Android Studio, I could then specify the former for Pull... and the
latter for Push…

It tends to default to what you have selected, but each time check that it
has selected the correct remote and the correct branch "master".

**Comment by eldelinux** [comment]
Hi Peter.

I installed an other version of AS in computer (Android Studio 3.2.1 Build #AI-181.5540.7.32.5056338 with JRE: 1.8.0_152-release-1136-b06 amd64, JVM: OpenJDK 64-Bit Server VM, Linux 4.15.0-29deepin-generic) downloaded of official AS web page, and I need to do tests with a new PR.  In addition I installed AS in old computer with Windows 10 (it's very slow). 

I see an a conflict with files strings.xml in my last PR, l think that first I should resolve this conflict.

Luis Zamora (eldelinux).

**Comment by flash62au** [comment]
sounds good.

There were a lot of new strings added for the Permissions and Intro
Screens, but I don't believe any of the existing strings were changed, so
it hopefully is just a matter of AS being a bit confused.

P.S. when you get a chance I would appreciate it if you can look at the new
strings as well, as I have only done Google Translations for them.

Peter

**Comment by eldelinux** [comment]
Hi Peter.

Thanks for your patience, but I'm confused, in this PR at Github have a conflicting files strings.xml for catalan and spanish translation, and in AS the local file strings.xml (ca and es), I can see the new strings that you added, these new strings are marked with a comment with "", but I don't see any conflict. I deduce that the new strings are commented, so they are reviewed for the translator. But, where are the conflict?.

In addition, I don't know if the new AS 3.2.1 work well with the PR.

Thanks a lot....

**Comment by flash62au** [comment]
Hi,
Sorry I didn't fully explain.

I would delete (and otherwise ignore) the PR on github.
Then use the 'Compare Directories' plugin to compare the new repository to
the copy you kept, to recreate your changes.
Then commit, push and create a new PR.

Peter

**Comment by eldelinux** [comment]
Closing this PR, I'm working on the ca-es translations of new strings added for make a new PR, and verify with this new PR the new version of AS of my PC (the previous AS version generated conflict with Gradle files).

**Pull request closed without merging**
