### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by mstevetodd**

### CODE REVIEW

**Comment by mstevetodd** [comment]
trying to accept pull request for new readme for enginedriver

**Comment by bobjacobsen** [comment]
Is this working for you?

**Comment by mstevetodd** [comment]
Hi Bob,
No, I cloned the repo, added a file and created a pull request back to JMRI/ENGINEDRIVER, but I can't figure out how to accept the pull request.  Maybe I don't have write access?

**Comment by rhwood** [comment]
@mstevetodd You need to accept the invitation we sent for you to join the EngineDriver team. It was sent a couple of weeks ago. Once you accept the invitation, you will automatically get write access.

**Comment by mstevetodd** [comment]
Ok, thanks.  I thought I had already done that.  Working now, from the web at least.  On to Eclipse and Android Studio!

**Pull request merged**
