### PR TITLE
Add support for ESU MobileControl II throttle

### PR DESCRIPTION
**Pull request by mattharris**
This PR adds support for the ESU MobileControl II Android throttle.

### CODE REVIEW

**Comment by mstevetodd** [comment]
@mattharris Thank you for submitting this! 
Robin @n3ix is going to review and test this PR, since he now has one of these gadgets.
I'd like to publish 2.16 with the several months of fixes and enhancements before merging your work to be part of 2.17. Hopefully, that'll only be a couple of outstanding bug fixes that you'll need to add into this PR.

**Comment by mattharris** [comment]
@mstevetodd Thanks for that. Any rough idea on release timeline for 2.16 & 2.17?

@n3ix If it helps, to save you the hassle of checking out this PR, the compiled apk containing these updates can be found at:

https://1drv.ms/u/s!AknsBAA5dKchg3WrPqjqEcQRqZJz

This contains the current HEAD of master, along with the ESU MCII related updates.

**Comment by n3ix** [comment]
@mattharris <https://github.com/mattharris>  There is a problem with the throttle knob power drive - the throttle knob is not consistently returning (CW) to the zero position after full CCW rotation.  Works first time, then fails if I move back to the Stop.  Increasing the speed via the SLIDER or BUTTONS sometimes resolves the issue.  I did not see this behavior with the ESU demo so I suspect it is a code problem?

 

Robin

**Comment by n3ix** [comment]
@mattharris <https://github.com/mattharris>  There is a problem with the throttle knob power drive - the throttle knob is not consistently returning (CW) to the zero position after full CCW rotation.  Works first time, then fails if I move back to the Stop.  Increasing the speed via the SLIDER or BUTTONS sometimes resolves the issue.  I did not see this behavior with the ESU demo so I suspect it is a code problem?

 

Robin

**Comment by mstevetodd** [comment]
@mattharris 2.16 should be published this week, and 2.17 could be published whenever you and Robin agree the ESU enhancement is good to go.

**Comment by mattharris** [comment]
@n3ix Do you have the logcat output and/or a reproducible scenario to trigger the issue? Any request to move the control knob is in logcat - all relevant log messages are prefixed 'ESU_MCII:'.

**Comment by n3ix** [comment]
@mattharris I was just running your APK on the railroad so no log info from first test.  Now back at PC and connected to Steve’s test jmri connection.  Logcat info follows.

 

Failed to move from full CCW:

01-03 11:41:56.190 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button down for throttle T

01-03 11:41:56.190 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Attempting to switch direction

 

 

Succeeded in moving off of full CCW:

01-03 11:43:24.180 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button down for throttle T

01-03 11:43:24.180 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Attempting to switch direction

01-03 11:43:24.390 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button up for throttle T

01-03 11:43:25.930 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob position changed for throttle T

01-03 11:43:25.930 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: New knob position: 1 ; speedstep: 0

**Comment by n3ix** [comment]
Partial movement off fully CCW

 

01-03 11:45:41.680 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button down for throttle T

01-03 11:45:41.680 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Attempting to switch direction

01-03 11:45:42.090 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button up for throttle T

 

 

From: Robin Becker [mailto:rbgroups@n3ix.com] 
Sent: Wednesday, January 03, 2018 11:44 AM
To: 'JMRI/EngineDriver' <reply@reply.github.com>; 'JMRI/EngineDriver' <EngineDriver@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [JMRI/EngineDriver] Add support for ESU MobileControl II throttle (#131)

 

@mattharris I was just running your APK on the railroad so no log info from first test.  Now back at PC and connected to Steve’s test jmri connection.  Logcat info follows.

 

Failed to move from full CCW:

01-03 11:41:56.190 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button down for throttle T

01-03 11:41:56.190 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Attempting to switch direction

 

 

Succeeded in moving off of full CCW:

01-03 11:43:24.180 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button down for throttle T

01-03 11:43:24.180 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Attempting to switch direction

01-03 11:43:24.390 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button up for throttle T

01-03 11:43:25.930 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob position changed for throttle T

01-03 11:43:25.930 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: New knob position: 1 ; speedstep: 0

**Comment by mattharris** [comment]
@n3ix Just to be sure, what do you mean by 'CW' and 'CCW'?

And it might be that we were both running on Steve's test connection around the same time as I did notice once or twice having my loco stolen.

**Comment by mattharris** [comment]
@n3ix It's OK - just realised that you're talking about clockwise versus anti-clockwise (I'm British - yet another term that's different between English and American!!)

**Comment by mattharris** [comment]
Seems like in the first case, the end-stop switch 'up' was not recorded. When releasing the control knob after hearing the 'click' of the end-stop switch, the knob should rotate slightly clockwise to rest at the zero position.

**Comment by n3ix** [comment]
@mattharris <https://github.com/mattharris>  There are variations that appear but the common thread might be that the motor is not powered long enough (or at all) following the full CCW (yes counterclockwise :), sorry about the shorthand) rotation to get the knob back to the zero position.  Just tried doing it several times in a row.  The first time it went back to zero.  The second time maybe halfway.  The third time it barely moved.  Eventually it shows no movement at all.   In all cases the direction changed.

 

01-03 13:33:35.306 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button down for throttle T

01-03 13:33:35.306 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Attempting to switch direction

01-03 13:33:35.826 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button up for throttle T

01-03 13:33:37.776 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob position changed for throttle T

01-03 13:33:37.776 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: New knob position: 1 ; speedstep: 0

01-03 13:33:48.456 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button down for throttle T

01-03 13:33:48.456 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Attempting to switch direction

01-03 13:33:48.756 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button up for throttle T

01-03 13:33:51.936 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button down for throttle T

01-03 13:33:51.936 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Attempting to switch direction

01-03 13:33:52.246 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button up for throttle T

01-03 13:33:53.886 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button down for throttle T

01-03 13:33:53.886 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Attempting to switch direction

01-03 13:33:54.296 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button up for throttle T

01-03 13:33:55.836 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button down for throttle T

01-03 13:33:55.836 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Attempting to switch direction

01-03 13:33:56.456 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button up for throttle T

**Comment by mattharris** [comment]
I wonder if it might be related to the zero position calibration of the control knob and slight variations with manufacturing tolerances.

In the ESU Mobile Control II app, under settings (need to first be in either demo mode or linked to an ECoS), there is a 'Calibrate throttle' option. On the device I've got, after following the calibration steps, I typically get a calibrated zero position of 8.

The knob position to speed step translations use a position of 10 for the zero position (this is copied from ESU's API sample).

I've tried several attempts to replicate this issue without success - the only scenarios where control knob movements are not taken into account are when either no train is selected for control (flashing green LED), or when the device Stop 'button' (top-right just above screen) is pressed and we're in Pause/All-Stop mode (fast or slow flashing red LED).

In all other occasions with a solid green LED lit (meaning that a train is under control), turning the control knob, using the side buttons, dragging the seekbar, pressing increase/decrease on-screen buttons, all resulted in the speed being updated and knob moving appropriately.

Additionally, when a second (or third) train is being controlled, switching between the controlled trains (via either pressing on speed display or pressing the configured device button for next throttle - bottom-right by default) caused the control knob to move to the correct position.

If you could verify the zero position on your device, perhaps that could help identify a potential cause for this.

**Comment by n3ix** [comment]
I tried the Calibration procedure and the zero position is now 8.  The behavior improved but is not perfect.  The throttle now rotates back to zero or almost back to zero every time.  However there are a couple issues.  The speed of the rotation back to zero is not the same every time.   More importantly it appears that sometimes the knob rotation does not quite reach the zero position - when this happens the log does not show that the final “New knob position:…” message and the Slider and Throttle Setting numerical value remain at some prior non-zero setpoint.  

 

If I hold the knob at the full CCW position after rotation then it never returns all the way to the zero after I release the knob and the speed never get sets to zero.

 

I am concerned that the speed is not getting updated prior to the ‘full counterclockwise click /  change direction / rotate back to zero’ process.  I can demonstrate this repeatedly.  Here is the log from a “normal” rotation of the knob back to the full CCW position.

 

01-04 08:38:07.211 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob position changed for throttle T

01-04 08:38:07.211 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: New knob position: 13 ; speedstep: 1

01-04 08:38:07.431 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button down for throttle T

01-04 08:38:07.431 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Attempting to switch direction

01-04 08:38:07.631 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button up for throttle T

01-04 08:38:08.541 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob position changed for throttle T

01-04 08:38:08.541 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: New knob position: 8 ; speedstep: 0

 

Notice that the “Knob button down” occurs at 8:38:07.431 so the knob is fully rotated CCW at that point, but there is no speedstep 0 command until 1 second later.  This does not seem good.  If I hold the knob at the CCW position there will be no speedstep 0 command until after I release the knob and it returns to zero (if it makes it back that far).  

 

So it appears that the knob position sampling rate is slow enough that there can easily be no sample corresponding to speedstep 0 as the knob is moved to the full CCW position.  As a minimum it appears we need a speedstep 0 generated following the “Knob button down for throttle T”?

**Comment by n3ix** [comment]
FYI here is another example where it took 3 minutes before the speedstep 0 appeared following a full CCW rotation:

 

01-04 08:50:45.470 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob position changed for throttle T

01-04 08:50:45.470 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: New knob position: 25 ; speedstep: 7

01-04 08:50:45.680 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button down for throttle T

01-04 08:50:45.680 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Attempting to switch direction

01-04 08:50:47.120 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button up for throttle T

01-04 08:53:44.110 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob position changed for throttle T

01-04 08:53:44.110 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: New knob position: 5 ; speedstep: 0

 

Just kind of reinforces the need to generate a speedstep 0 upon “Knob button down for throttle T” ?

 

From: Robin Becker [mailto:rbgroups@n3ix.com] 
Sent: Thursday, January 04, 2018 8:50 AM
To: 'JMRI/EngineDriver' <reply@reply.github.com>; 'JMRI/EngineDriver' <EngineDriver@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [JMRI/EngineDriver] Add support for ESU MobileControl II throttle (#131)

 

I tried the Calibration procedure and the zero position is now 8.  The behavior improved but is not perfect.  The throttle now rotates back to zero or almost back to zero every time.  However there are a couple issues.  The speed of the rotation back to zero is not the same every time.   More importantly it appears that sometimes the knob rotation does not quite reach the zero position - when this happens the log does not show that the final “New knob position:…” message and the Slider and Throttle Setting numerical value remain at some prior non-zero setpoint.  

 

If I hold the knob at the full CCW position after rotation then it never returns all the way to the zero after I release the knob and the speed never get sets to zero.

 

I am concerned that the speed is not getting updated prior to the ‘full counterclockwise click /  change direction / rotate back to zero’ process.  I can demonstrate this repeatedly.  Here is the log from a “normal” rotation of the knob back to the full CCW position.

 

01-04 08:38:07.211 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob position changed for throttle T

01-04 08:38:07.211 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: New knob position: 13 ; speedstep: 1

01-04 08:38:07.431 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button down for throttle T

01-04 08:38:07.431 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Attempting to switch direction

01-04 08:38:07.631 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob button up for throttle T

01-04 08:38:08.541 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: Knob position changed for throttle T

01-04 08:38:08.541 1461-1461/jmri.enginedriver D/Engine_Driver: ESU_MCII: New knob position: 8 ; speedstep: 0

 

Notice that the “Knob button down” occurs at 8:38:07.431 so the knob is fully rotated CCW at that point, but there is no speedstep 0 command until 1 second later.  This does not seem good.  If I hold the knob at the CCW position there will be no speedstep 0 command until after I release the knob and it returns to zero (if it makes it back that far).  

 

So it appears that the knob position sampling rate is slow enough that there can easily be no sample corresponding to speedstep 0 as the knob is moved to the full CCW position.  As a minimum it appears we need a speedstep 0 generated following the “Knob button down for throttle T”?

**Comment by mattharris** [comment]
@n3ix the knob position isn't being explicitly sampled in the EngineDriver additions - we just hook into the ESU provided API callbacks.

What _might_ be worth verifying is the version of ESU Input Services on your device to make sure that's up-to-date - the latest public version is 1.07 (goto Settings > Apps > ESU Input Services). To update, you will need to download the firmware updater from the ESU website.

**Comment by n3ix** [comment]
@mattharris <https://github.com/mattharris>  Yes my device has ESU Input Services V1.07.  There could certainly be a mechanical issue in the device that was sent to me.   To compare apps, I did some testing with the ESU app in demo mode and the speed of movement back to zero from full CCW sometimes is slower.  However the knob gets back to zero almost all of the time using the ESU app, certainly very different behavior than I’m seeing with EngineDriver.

 

I haven’t looked at your code changes yet, do you handle a callback for “Knob button down for throttle T”?  If so maybe explicitly setting the speed to zero there would be a good idea regardless of whatever else is going on?

**Comment by mattharris** [comment]
I've updated this PR with the changes on master and have included knob move requests on speedUpdateAndNotify (as opposed to just speedChangeAndNotify).

Whilst I wasn't seeing issues with knob updates when testing, it's possible there were some codepaths that I wasn't passing through. Hopefully these modifications will resolve the missed knob movements @n3ix was seeing.

I've updated the pre-built .apk (same link as before) - it's now version 2.17-test1

**Comment by n3ix** [comment]
Downloaded and installed the new APK.  No change in behavior.  If I adjust the throttle for a high speed, say 40, and then quickly rotate the knob CCW all the way to the stop, the speed often reads non-zero.  Now if the know does not rotate all the way back to the stop by the motor, which often happens, the speed stays non-zero.  See attached photo.

 

This is very repeatable.  After rotating the knob to the stop, holding the knob briefly at the stop and then releasing it will almost always result in this behavior.

 

Robin

**Comment by n3ix** [comment]
After sitting idle in the previously described “stuck” state with non-zero throttle value for several minutes, the speed changed to zero.  This seems to be repeatable so thought this info it might be useful.

 

Robin

 

 

From: Robin Becker [mailto:rbgroups@n3ix.com] 
Sent: Friday, January 12, 2018 7:54 AM
To: 'JMRI/EngineDriver' <reply@reply.github.com>; 'JMRI/EngineDriver' <EngineDriver@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [JMRI/EngineDriver] Add support for ESU MobileControl II throttle (#131)

 

Downloaded and installed the new APK.  No change in behavior.  If I adjust the throttle for a high speed, say 40, and then quickly rotate the knob CCW all the way to the stop, the speed often reads non-zero.  Now if the know does not rotate all the way back to the stop by the motor, which often happens, the speed stays non-zero.  See attached photo.

 

This is very repeatable.  After rotating the knob to the stop, holding the knob briefly at the stop and then releasing it will almost always result in this behavior.

 

Robin

**Comment by n3ix** [comment]
After sitting idle in the previously described “stuck” state with non-zero throttle value for several minutes, the speed changed to zero.  This seems to be repeatable so thought this info it might be useful.

 

Robin

 

 

 

From: Robin Becker [mailto:rbgroups@n3ix.com] 
Sent: Friday, January 12, 2018 7:54 AM
To: 'JMRI/EngineDriver' <reply@reply.github.com>; 'JMRI/EngineDriver' <EngineDriver@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [JMRI/EngineDriver] Add support for ESU MobileControl II throttle (#131)

 

Downloaded and installed the new APK.  No change in behavior.  If I adjust the throttle for a high speed, say 40, and then quickly rotate the knob CCW all the way to the stop, the speed often reads non-zero.  Now if the know does not rotate all the way back to the stop by the motor, which often happens, the speed stays non-zero.  See attached photo.

 

This is very repeatable.  After rotating the knob to the stop, holding the knob briefly at the stop and then releasing it will almost always result in this behavior.

 

Robin

**Comment by mattharris** [comment]
@n3ix I didn't get the image as GitHub seems to strip attachments via email - you'll need to attach it directly to the PR on GitHub.

Anyhow, I've tried with a quick twist back & forth of the knob on my device, and it seems to track that without problem

I've uploaded a quick video of this at: https://youtu.be/PC-Sk6V0YPM (it's really rough as I was trying to juggle my mobile phone and throttle at the same time - you'd better turn the sound down unless you want to be startled by the noise as it slips from being propped-up by my keyboard partway through...)

To me, it sounds like there _might_ be a problem with your device.

**Comment by n3ix** [comment]
ed with stuck knob and non-zero speed
Here is a photo of my device in the "stuck" mode.  The knob is between the zero position and the CCW stop, and the speed is non-zerol

**Comment by mattharris** [comment]
@n3ix I've just updated this with an explicit zero speedUpdate when end-stop switch press is detected. Could you try the revised .apk (same URL as before) to see if this fixes the issue you were seeing.

I was able to reproduce a similar effect, although the zero position was recorded immediately after release of the knob from the end-stop. With this latest update, I was unable to reproduce this.

Thanks for your help.

**Comment by n3ix** [comment]
@mattharris Progress!  Speed now gets set to 0 when at the stop.  If I rotate CCW quickly and stop just short of the stop put beyond the expected zero point, I can still sometimes get a non-zero speed.  

Interesting to note that I can get similar behavior with the ESU app in demo mode.  If I rotate quickly CCW all the way to the stop and hold there, I can get non-zero speed.  I can also get the demo app to occasionally fail to restore the knob all the way to zero.  Much less frequently than EngineDriver, but it does happen.  Wonder why it is harder to produce in the ESU app?

Seems like all we can do at this point, but I think ESU / Jurgen will need to comment on this behavior.  Once ED is running on this device, the support requests will come to the ED team and I think we ought to know whether this is fixable or by-design.  Agree?

**Comment by mattharris** [comment]
@n3ix thanks for the confirmation of those changes getting us closer.

I've just added the possibility to adjust the zero trim as a preference option, and made sure that the zero trim is applied everywhere. I've also arranged the ESU MCII preferences a bit more logically and added range checking to the numeric ones.

Also, the apk has been updated to incorporate these latest updates.

**Comment by n3ix** [comment]
@mattharris  Loaded the latest apk.  I tried setting the zero trim to 20 (it was 10) and now the knob reliably returns to zero.  So I set it back to 10 and it continued to work - it does should signs of sticking (slowing down) during the return to zero move but eventually makes it.  Next I exited ED and restarted and the problem behavior returned.  This time I set the zero to 12 and things seems good.  Exited and restarted ED.  Problem behavior returned.  Checked the prefs - zero is still set to 12.  Hmm.

Ok, think I noticed something.  I set the zero offset to 20.  Exited and restarted ED.  The knob moved back to the "offset of 10" position on start!  I checked the prefs and the offset was still set to 20.  I think this is a clue, agree?

**Comment by n3ix** [comment]
@mattharris Zero position seems good now!  I set the zero point back to a value of 10 and the knob always returns to zero after full CCW rotation.  Nice work, interesting problem to track done.

**Comment by mattharris** [comment]
OK, we seem pretty much OK now on this - I'm going to go ahead and merge.

There might be one or two minor improvements, but I'll handle those in separate PRs.

**Pull request merged**
