### PR TITLE
Individually control the lights of the Locos in a Consist

### PR DESCRIPTION
**Pull request by flash62au**
Option to individually control the lights of the Locos in a Consist with a long click on the Loco Select button.

### CODE REVIEW

**Comment by flash62au** [comment]
Oops. Shall fix.

**Comment by flash62au** [comment]
I removed the toast message.
I found one piece of code that referred to the consist_Edit_menu. (in the onDestroy)
I removed a commented out section of code that I had left behind.
I only found one other place that still referred to Consist Edit in the comments.   Hopefully that is all of it.

**Comment by flash62au** [comment]
I have spent the night trying to find a way to tell how many Bt devices are connected with little success.
I can find the paired devices easily enough. 
Finding a list of GATT devices connected is easy enough. (Doesn't help as the gamepads are not GATT).

All my reading to-date says that only ways to find the connected devices is:
- to listen for connection events.   Presumably won't work if it is already connected.
- attempt  to open a socket for each paired device.  This seems inefficient.  (I assume you will have to wait for each attempt to pass/fail)

Any thoughts?

Peter

**Comment by flash62au** [comment]
Robin,
I have added a check of the arguments, but I not entirely sure that I have interpreted your directions correctly.

Peter

**Comment by flash62au** [comment]
I have left the check in for the actual paired BT devices, but this requires an extra permission, and doesn't offer a great deal of value.  

Should I take it out?

**Comment by mstevetodd** [comment]
Yes, if its not adding value, please remove. I'd prefer to minimize the permissions to only those strictly required.

**Comment by n3ix** [comment]
Can these 3 imports be removed from Throttle now?
import android.bluetooth.BluetoothAdapter; 
import android.bluetooth.BluetoothManager; 
import android.bluetooth.BluetoothDevice;

**Comment by flash62au** [comment]
Missed them in the clean up.
Shall remove.

Peter

**Pull request merged**
