### PR TITLE
Permit ESU MCII control knob to be disabled

### PR DESCRIPTION
**Pull request by mattharris**
Following on from a user request, this PR provides a configurable option that displays an on-screen button allowing the control knob on the ESU MCII to be ignored.

### CODE REVIEW

**Comment by mattharris** [comment]
@mstevetodd One thing to note is that this PR also incorporates removal of the pre-compiled .jar for ESU MCII support, rather relying on the gradle dependency mechanism to pull from the central repository.

**Comment by mattharris** [comment]
@flash62au as the necessary files are now pulled from the central on-line repository (which is the recommended procedure for dealing with external libraries with Gradle), you should double-check that your Gradle settings in Android Studio are not set to 'Offline work':

image

Otherwise, perform a manual rebuild via 'Build' > 'Make Project':

image

**Comment by flash62au** [comment]
Hi,
'Offline work' was NOT checked.
I don't know if it makes a difference but when I setup the new version of
AS I could not get it to work until I used a local distribution of Gradle.

Doing a manual rebuild has resulted in a different error.. 'error: cannot
find symbol class Activity'

I Googled it and tried a few of the suggestions without luck.

Any thoughts?
Peter

**Comment by flash62au** [comment]
P.S.
I should have mentioned that error only occurs on

 */
public void toggleEsuMc2Knob(Activity activity, Menu menu) {
    if (isEsuMc2KnobEnabled) {
        isEsuMc2KnobEnabled = false;
    } else {

and


case R.id.EsuMc2Knob_button:
    toggleEsuMc2Knob(this, TMenu);
    break;



n GitHub

**Comment by mattharris** [comment]
Peter,

Not sure what you mean by 'including the imports' as these were not touched
by this update:

[image: image.png]

As you can see from the annotation, the imports were included back in
December last year when this support was initially added.

Now it's possible that there's something odd in your local environment wrt
Gradle - for me, this was built and developed on a complete vanilla
installation of Android Studio (v3.2.1) with a fresh checkout of the
EngineDriver source as it's on a new machine, meaning that there's no
historical 'cruft'...

Another possibility is forcing a resync of the project Gradle files via the
toolbar (I might have had to do that at some point during the change, but
cannot recall exactly):

[image: image.png]

or via the menu:

[image: image.png]

Also, is your 'master' branch in-line with that on GitHub, or has it
diverged? (Keeping up-to-date with upstream master is one of the reasons I
tend to not work on my local master, rather pretty much always in a branch).

Not sure what else I can suggest.

Best regards,

Matt H

**Comment by flash62au** [comment]
Hi,
I am very much an amateur at this so my apologies for the dumb questions.
 
In think I worked out what happened.  My fault.

Peter

**Comment by flash62au** [comment]
actually it is a bit more confusing than I thought.

I have a bunch of changes waiting in PR that included the removal of the
Activity import in throttle.java along with a number of other unused
imports.  I didn't explicitly delete the imports.
As an experiment I added one of the others back in, and AS immediately
removed it.

I think I have found the setting that is doing it and have hopefully
disabled it.

I assume that AS removed the Activity as it was unused.  (It wasn't used by
anything until you added the new code.)  Oddly, the pull from the main
repository added your code, but did not re-add the import.

Looks like I will have to manually re-add all the unused imports to bring
it back the same state as the main repository.

Peter

**Pull request merged**
