### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by sidlo64**

### CODE REVIEW

**Comment by flash62au** [comment]
Hi,
the translation is greatly appreciated.

Unfortunately you have included translations for a number of arrays and strings that must not be translated.  The code relies on the exact strings in these particular ones. (They don't appear in the UI and are only used in the code.)  Some functionality will be broken because the translations are there. 
There are also some others that don't require translation (mostly numbers) which may cause extra work later if the translation exists.

The arrays that must not be translated are easy to spot.  Any array with a name that ends in "...EntryValues" and for which there is corresponding one with a name that ends with "...Entries" (usually followed with a comment ).   The "..Entries"  one needs the translation.  The "...EntryValues" SHOULD NOT be in the arrarys.xml file.

The strings that should not be included is harder to work through.  They almost all end with "...DefaultValue", but unfortunately not all of them.  Some do need translations.
It is safe to exclude them if they only contain a number.

I will spend some time in the next day or two marking all the strings and arrays (on the default arrays.xml and strings.xml) that should not be translated, with a comment to that effect.

Peter Akers
Brisbane - Australia

**Comment by flash62au** [comment]
I have just gone through the files quickly and created a PR that tags the entries that should not be translated.
https://github.com/JMRI/EngineDriver/compare/master...flash62au:master
This may not be a 100% correct but will be fairly close.  I will have a closer look of the next day or so.

Can I ask that you remove the tagged entries from your file and re-commit.

thanks
Peter Akers
(Brisbane - Australia)

**Comment by sidlo64** [comment]
Yes, I fix it and re-commit.

**Comment by sidlo64** [comment]
I have all HTML files in UTF-8. There is declaration <html lang="en">. Is it correct?

**Comment by flash62au** [comment]
Hi,
The changes look good.

Not positive about UTF-8.  Steve will have to comment if it is a problem, but I would expect it is ok.

Peter

**Pull request merged**
