### PR TITLE
CHANGE - experimental coloured launcher icon

### PR DESCRIPTION
**Pull request by flash62au**
I put it in the v21 folders for the time being, just for the simplicity of changing or removing it.

### CODE REVIEW

**Comment by n3ix** [comment]
It looks ok but existing icon already has a colored background.  What was the reason for going to a partial colored background?  

In the new icon the background seems a bit too "yellow" to me.  The current background has a gradient and the color behind the engine looks darker than in the new one?

Maybe drop the periods in "E.D." and just show it as "ED"?  People can think that is the engineer's name :)

**Comment by flash62au** [comment]
It looks ok but existing icon already has a colored background. What was
the reason for going to a partial colored background?

A few reasons.

1. I didn't want to to look too different to the original.

2. Pet hate to have uniform icon backgrounds. E. G all round or all square,
etc.

3. I wanted to mimic the rounded black outlined box on the original icon,
which has the smoke coming outside the box.

I will go back to the rounded square.


In the new icon the background seems a bit too "yellow" to me.

I originally had it darker, but the loco looked dull against it. I can
change it back.


The current background has a gradient and the color behind the engine looks
darker than in the new one?

The original is a complex checkerboard, with a gradient or highlight in the
top left. I think personally think that it makes it look fuzzy.

I was trying to do something closer to the material design standards, which
recommends flat colours.

I will try a gradient.


Maybe drop the periods in "E.D." and just show it as "ED"? People can think
that is the engineer's name :)

Can do.


Peter

On 26 Jun. 2018 05:46, "Robin" <notifications@github.com> wrote:

It looks ok but existing icon already has a colored background. What was
the reason for going to a partial colored background?

In the new icon the background seems a bit too "yellow" to me. The current
background has a gradient and the color behind the engine looks darker than
in the new one?

Maybe drop the periods in "E.D." and just show it as "ED"? People can think
that is the engineer's name :)

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/JMRI/EngineDriver/pull/284#issuecomment-400072450>, or mute
the thread

**Comment by n3ix** [comment]
Peter, By all means follow the standard - if the background should be flat then go with it.  

With a transparent background behind the smoke, the visibility of the smoke will be dependent on the users wallpaper, correct?  FYI I cannot find any icon on my phone that has part of the image that extends beyond the background box.

If you could tweak the background color a bit that would be appreciated.  Again checking my phone, background colors that aren't White are all more saturated then the color in the new ED icon.

I kind of like "ED" but was half-joking.  Let's see what Steve thinks about this.

**Comment by flash62au** [comment]
Standards are meant to be broken :-)
I was trying to be 'closer' to the standard. I didn't expect to stick to it
entirely.

The smoke outside the box was just me try to be different.  I will ditch it.
I only have one app installed that does it, but that is text that extends
partly beyond the box. (actually a circle)  I have a few others that are
multiple joined objects with out a single 'box' as such.

I agree the background colour is a bit insipid.

Funny thing, I originally had just 'ED' but thought that people might
confuse it with the driver's name. :-)

I can go back to the full 'Engine Driver' text, but I don't see the need.
The icon is generally displayed with the app name under it anyway.

I have deliberately not done these as adaptive icons.  That will come next.

Peter

**Pull request merged**
